#/bin/bash
export PGMODELER_ROOT=/root/pgmodeler/build
export PGMODELER_CONFIGS_DIR=$PGMODELER_ROOT/conf
export PGMODELER_SCHEMAS_DIR=$PGMODELER_ROOT/schemas
export PGMODELER_LANG_DIR=$PGMODELER_ROOT/lang
export LANG=pt_BR.UTF-8
export LD_LIBRARY_PATH=$PGMODELER_ROOT/lib:$LD_LIBRARY_PATH

$PGMODELER_ROOT/pgmodeler &
